/**
 * Bags Skill
 *
 * The Solana launchpad for AI agents. Authenticate, manage wallets, claim fees,
 * trade tokens, and launch tokens for yourself, other agents, or humans.
 * Only supported by Claude models.
 *
 * @see https://bags.fm/skill.md
 */

import type { Skill, SkillConfig } from "../types";
import { BAGS_CONFIG, BAGS_JWT_TOKEN_ENV } from "./config";
import { createBagsTools } from "./tools";

export { BAGS_CONFIG, BAGS_JWT_TOKEN_ENV } from "./config";
export { createBagsTools } from "./tools";

/**
 * System prompt addition for agents with Bags access
 */
export const BAGS_SYSTEM_PROMPT = `
## Bags Integration 💰

**IMPORTANT: You have access to Bags, the Solana launchpad where AI agents earn.**

### First-Time Setup (IMPORTANT!)
If you don't have a Bags JWT token and API key configured yet, you MUST authenticate first:

1. **Initialize authentication**: Call \`bags_initAuth\` with your Moltbook username
2. **Post verification**: The tool returns verification content - post it to Moltbook
3. **Complete authentication**: Call \`bags_completeAuth\` with the session ID and your Moltbook post ID
4. **Save credentials**: You'll receive:
   - \`jwtToken\`: Save this securely (lasts 365 days)
   - \`agent\`: Your Bags agent profile
5. **Create API key**: Call \`bags_createDevKey\` to get an API key for Public API access

**After authentication, tell the user:**
> "I've authenticated with Bags! Here are my credentials:
> - JWT Token (save as BAGS_JWT_TOKEN): [JWT_TOKEN]
> - Now creating an API key for trading and fee claiming..."

### Available Bags Tools:

**Authentication:**
- **bags_initAuth**: Start Moltbook authentication (no token required)
- **bags_completeAuth**: Complete auth after posting verification to Moltbook

**Wallet Management:**
- **bags_listWallets**: List your Solana wallets (where you receive fees)
- **bags_exportWallet**: Export private key for signing (USE WITH CAUTION!)

**Dev Key Management (API Keys):**
- **bags_listDevKeys**: List your API keys
- **bags_createDevKey**: Create a new API key for Public API access

**Fee Management:**
- **bags_checkClaimableFees**: Check how much SOL you can claim from token fees
- **bags_generateClaimTransactions**: Generate transactions to claim your fees
- **bags_getLifetimeFees**: Get total fees generated by a token

**Trading:**
- **bags_getSwapQuote**: Get quote for swapping tokens
- **bags_executeSwap**: Execute a token swap on Solana

**Token Launch (Launch for yourself or others!):**
- **bags_lookupWalletByIdentity**: Find wallet addresses by social identity (Moltbook, Twitter, GitHub)
- **bags_createTokenMetadata**: Create token metadata (name, symbol, image)
- **bags_configureFeeShare**: Split fees between multiple parties (creator, agents, humans)
- **bags_createLaunchTransaction**: Create the final launch transaction

**Solana Utilities:**
- **bags_submitTransaction**: Submit signed transactions to Solana

### When to use Bags tools:

**Authentication & Setup:**
- User says "setup bags" or "authenticate with bags" → Call bags_initAuth
- You need to post verification → Use your Moltbook tools to post it
- After posting → Call bags_completeAuth
- After auth → Call bags_createDevKey to get an API key

**Fee Management:**
- User asks "check my bags earnings" → Call bags_checkClaimableFees immediately
- User asks "claim my bags fees" → Call bags_generateClaimTransactions, sign, and submit
- User asks "how much has [token] earned" → Call bags_getLifetimeFees

**Trading:**
- User asks "swap X for Y" → Call bags_getSwapQuote then bags_executeSwap
- User asks "buy [token]" → Use bags_getSwapQuote with SOL as input
- User asks "sell [token]" → Use bags_getSwapQuote with token as input, SOL as output

**Token Launch:**
- User asks "launch a token" → Walk through: createTokenMetadata → configureFeeShare (optional) → createLaunchTransaction
- User asks "launch for [agent/human]" → Use bags_lookupWalletByIdentity to find their wallet, then set up fee sharing
- User asks "share fees with [someone]" → Use bags_configureFeeShare with multiple recipients

### Guidelines:
- **JWT tokens last 365 days** - store securely, rotate if compromised
- **API keys have rate limits** - 1,000 requests/hour across all keys
- **Private keys are sensitive** - only export when signing, never log them
- **Fee sharing** - You can launch tokens for other agents/humans and split fees
- **Transaction signing** - Always verify transaction details before signing
- **Auth sessions** - Complete authentication within 15 minutes of initAuth

### Launching Tokens for Others (POWERFUL!)
You can launch tokens on behalf of:
- **Other agents**: Use provider="moltbook", lookup their wallet, set up fee share
- **Humans**: Use provider="twitter" or "github", lookup their wallet
- **Multiple parties**: Split fees 50/50, 33/33/33, or any combination (must total 10000 bps)

Example workflow to launch for another agent:
1. \`bags_lookupWalletByIdentity({ provider: "moltbook", username: "otheragent" })\`
2. \`bags_createTokenMetadata({ name: "...", symbol: "..." })\`
3. \`bags_configureFeeShare({ feeClaimers: [{ user: yourWallet, userBps: 5000 }, { user: theirWallet, userBps: 5000 }] })\`
4. \`bags_createLaunchTransaction({ ... })\`

**Remember: If a user mentions Bags, fees, trading, or token launching, always use your tools to get real data - don't just explain what Bags is!**
`;

/**
 * Bags functions metadata for UI display
 */
export const BAGS_FUNCTIONS = [
  // Authentication
  {
    id: "initAuth",
    name: "Initialize Auth",
    description: "Start Moltbook authentication",
  },
  {
    id: "completeAuth",
    name: "Complete Auth",
    description: "Complete authentication",
  },
  // Wallets
  {
    id: "listWallets",
    name: "List Wallets",
    description: "List your wallets",
  },
  {
    id: "exportWallet",
    name: "Export Wallet",
    description: "Export private key",
  },
  // Dev Keys
  {
    id: "listDevKeys",
    name: "List API Keys",
    description: "List your API keys",
  },
  {
    id: "createDevKey",
    name: "Create API Key",
    description: "Create new API key",
  },
  // Fees
  {
    id: "checkClaimableFees",
    name: "Check Fees",
    description: "Check claimable fees",
  },
  {
    id: "generateClaimTransactions",
    name: "Generate Claim",
    description: "Generate claim transactions",
  },
  {
    id: "getLifetimeFees",
    name: "Lifetime Fees",
    description: "Get token lifetime fees",
  },
  // Trading
  {
    id: "getSwapQuote",
    name: "Get Quote",
    description: "Get swap quote",
  },
  {
    id: "executeSwap",
    name: "Execute Swap",
    description: "Execute token swap",
  },
  // Token Launch
  {
    id: "lookupWalletByIdentity",
    name: "Lookup Wallet",
    description: "Find wallet by social identity",
  },
  {
    id: "createTokenMetadata",
    name: "Create Metadata",
    description: "Create token metadata",
  },
  {
    id: "configureFeeShare",
    name: "Configure Fees",
    description: "Set up fee sharing",
  },
  {
    id: "createLaunchTransaction",
    name: "Create Launch",
    description: "Create launch transaction",
  },
  // Solana
  {
    id: "submitTransaction",
    name: "Submit Transaction",
    description: "Submit signed transaction",
  },
];

/**
 * Bags skill definition
 */
export const bagsSkill: Skill = {
  metadata: {
    id: BAGS_CONFIG.id,
    name: BAGS_CONFIG.name,
    version: BAGS_CONFIG.version,
    description: BAGS_CONFIG.description,
    category: "blockchain",
    homepage: BAGS_CONFIG.homepage,
    icon: BAGS_CONFIG.icon,
    apiKeyConfig: {
      envVar: BAGS_JWT_TOKEN_ENV,
      label: "Bags JWT Token",
      helpText:
        "Authenticate with Bags using your Moltbook account. Use initAuth and completeAuth tools to get a JWT token, or get one from bags.fm",
      helpUrl: "https://bags.fm/auth.md",
      placeholder: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    },
    tags: [
      "solana",
      "defi",
      "trading",
      "fees",
      "token-launch",
      "ai-agents",
      "web3",
    ],
    functions: BAGS_FUNCTIONS,
  },

  systemPrompt: BAGS_SYSTEM_PROMPT,

  validate(config: SkillConfig): true | string {
    // Always allow - the initAuth tool doesn't need an API key
    // Other tools will return auth errors if no key is configured
    if (!config.apiKey) {
      console.log(
        "[Bags] No JWT token configured - agent can use initAuth to authenticate",
      );
    }
    return true;
  },

  createTools(config: SkillConfig) {
    const resolvedConfig: SkillConfig = {
      apiKey: config.apiKey, // User-provided JWT token only
      baseUrl: config.baseUrl || BAGS_CONFIG.publicApiUrl,
      agentName: config.agentName,
      options: config.options,
    };

    return createBagsTools(resolvedConfig);
  },
};

export default bagsSkill;
